version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - "/app/node_modules"
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=nazmul
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
